// prototypes/framework-bench/react-app/src/main.jsx
import { memo, useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { flushSync } from "react-dom";
import { useVirtualizer } from "@tanstack/react-virtual";
import { runBench } from "../../shared/bench-core.js";
import "../../shared/bench.css";

const Row = memo(function Row({ item, focused, y }) {
  return (
    <div
      className={focused ? "row focused" : "row"}
      style={{ transform: `translateY(${y}px)` }}
    >
      <span className="name">{item.name}</span>
      <span className="kind">{item.kind}</span>
      <span className="size">{item.size}</span>
    </div>
  );
});

let api = null;

function App() {
  const [items, setItems] = useState([]);
  const [focus, setFocus] = useState(0);
  const parentRef = useRef(null);

  const virtualizer = useVirtualizer({
    count: items.length,
    getScrollElement: () => parentRef.current,
    estimateSize: () => 28,
    overscan: 10,
  });

  useEffect(() => {
    api = {
      setItems,
      setFocus,
      scrollToIndex: (i) => virtualizer.scrollToIndex(i),
      scrollElement: () => parentRef.current,
    };
  });

  return (
    <div className="scroller" ref={parentRef}>
      <div className="inner" style={{ height: virtualizer.getTotalSize() }}>
        {virtualizer.getVirtualItems().map((v) => {
          const it = items[v.index];
          return it ? (
            <Row key={it.id} item={it} focused={v.index === focus} y={v.start} />
          ) : null;
        })}
      </div>
    </div>
  );
}

createRoot(document.getElementById("root")).render(<App />);

const adapter = {
  setup(items) {
    flushSync(() => {
      api.setItems(items);
      api.setFocus(0);
    });
  },
  setFocus(i) {
    flushSync(() => api.setFocus(i));
    api.scrollToIndex(i);
  },
  appendRows(rows) {
    flushSync(() => api.setItems((prev) => [...prev, ...rows]));
  },
  swapItems(items) {
    flushSync(() => api.setItems(items));
  },
  scrollElement: () => api.scrollElement(),
};

(async function start() {
  while (!api) {
    await new Promise((r) => requestAnimationFrame(r));
  }
  runBench(adapter);
})();

// prototypes/framework-bench/solid-app/src/main.jsx
import { createSignal, For } from "solid-js";
import { render } from "solid-js/web";
import { createVirtualizer } from "@tanstack/solid-virtual";
import { runBench } from "../../shared/bench-core.js";
import "../../shared/bench.css";

const [items, setItems] = createSignal([]);
const [focus, setFocus] = createSignal(0);

let parentEl;
let virtualizer;

function App() {
  virtualizer = createVirtualizer({
    get count() {
      return items().length;
    },
    getScrollElement: () => parentEl,
    estimateSize: () => 28,
    overscan: 10,
  });

  return (
    <div class="scroller" ref={parentEl}>
      <div class="inner" style={{ height: `${virtualizer.getTotalSize()}px` }}>
        <For each={virtualizer.getVirtualItems()}>
          {(v) => {
            const it = () => items()[v.index];
            return (
              <div
                class="row"
                classList={{ focused: focus() === v.index }}
                style={{ transform: `translateY(${v.start}px)` }}
              >
                <span class="name">{it()?.name}</span>
                <span class="kind">{it()?.kind}</span>
                <span class="size">{it()?.size}</span>
              </div>
            );
          }}
        </For>
      </div>
    </div>
  );
}

render(() => <App />, document.getElementById("root"));

const adapter = {
  setup(list) {
    setItems(list);
    setFocus(0);
  },
  setFocus(i) {
    setFocus(i);
    virtualizer.scrollToIndex(i);
  },
  appendRows(rows) {
    setItems((prev) => [...prev, ...rows]);
  },
  swapItems(list) {
    setItems(list);
  },
  scrollElement: () => parentEl,
};

requestAnimationFrame(() => {
  runBench(adapter);
});
